---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-credentials
  namespace: default
spec:
  encryptedData:
    postgres-password: AgBpaiEDEl9pQU4SdEGaWeAD4UIncExXWIMv0E9MsITm/xfBtQN3Y1ygaSlg2Pi/pRvWmaBRIs/2Y+7onIwnN/jpOM/Gckhsn/jhvZ5zdHoky0RjVZ4iorKIr1nfit9ELIAwyNCVVylPrkPzWvHeWsVtVzkJY6r0GWmL/Eh/jkXa2XEE+CLpbLyYOE5weOwIP0gGFSxO5Kee0QiD2EQhJN1hJqSx+Ny4Yb189gRS9kiZZHv8dBxDXwXOpngImgirOR69IpbsvCHAqOayVsu9CfKUeaLbmS/tCXZEDnYiOdN5tjdnNJDGpbyG/x+bkQGMZlChgVczV8PK+6rILaMU674g4raEzzw1pjIzES43dLTw0YduaabM6zJVID8LIb7krA0LnY9TAbeMwDHDhGq5hT6H/uUe6p80IKoL7ouHzNM378mPtVQx+5HR11ADYViYVGwdSbT4WZEUamZ4bAH0awlrGJq98m6JP1rH8cf8+BXWDdReHZV69pDroaQOVGC0EpgyoqApM27270gaCn8TPxsoxQyzw9UybruC2JxCY0AwW86PPgyEy8c9HlCKHtf0qmRJqNfUiq5CXBS8LJqs0jsLCnKvYMO9UwirsEn515DpQxNDwvfHgD+H6yli0zee6wublzTK22AXiT0sVYj8I/a1wwKQWsFhKrelSqxBSyBrimJ/LfuPadvkss2+yYTTgc1MnC23URboe6wEstbXR5Q=
    postgres-user: AgBiRSge6g/MVIvtw5EXp+juzEc3AF6K7KHhjFFaWkVpKRnMTV9dO9aU/8yotMwS7AAFakbbJCTEqpf+Yo4EOfLBMREjEdbYCRJOSUG3S89Q7a+bo0xekxaQBFdPSBAxXcLFui0wUwXENAOe+W/RqsK6zu7lBI55E1IUY7sflz5soKo0MafvL3kEobMZ1gUaJLECTNYochNqFNpmZUZQAxid+gVRxEHqJPxQ2R+wbgManSijlduQwrtOFwbliS58Eco4zr8AFUM2FeFlroOREuneDp60Kq9dPLOf6GtfYFu2GvhVbBTBHVVuLMltkdFGo5Bd4O8svwhavgknUdgFrchIBDwMO+eebKYJPZofXuVzw2VcL6AANEyvFCh6WkNzAQOIWsmXVOYxneAdVHcKITKGjGSZv1al6XJ74bNPmsF7wzH+uV+yr7pDiLmDeVkjNxO8dyzvQc7c0uQYfmBqQSNWHOykzkJti8H3U0X6mmWi3GQuz1dF+x0Uod3nvz9kpAh0YPjig5bGCWvf/VFEeKzTrmSILM+ElQwEsS8S1XFwa61ttrx1YWIw9M2VlLkJO9RF6d8qdS3vYRSbWXBt99+J6zLqgKx0crniFCQyBMfGX5OVXDOiaywxQw6wdE8Edyd779NxRYowcMtQLdl574M7BVdT2dF2UB0VcFyQZ9CHM6bIw0b29sDEac22R7TLLqOaTjHk3hg8Iw==
  template:
    metadata:
      creationTimestamp: null
      name: db-credentials
      namespace: default
