apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: therealpad/formationchatgpt-worker:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_HOST
              value: redis-service
            - name: POSTGRES_HOST
              value: db-service
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: postgres-password
          ports:
            - containerPort: 80
